### ISSUE TITLE
Error while encrypting result file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dobesv/gwt-distcc#3]
```
Saw this error while running a build:

{{{
SEVERE: Build failed
java.lang.ArrayIndexOutOfBoundsException
      at java.lang.System.arraycopy(Native Method)
      at com.sun.crypto.provider.SunJCE_f.b(DashoA13*..)
      at com.sun.crypto.provider.SunJCE_f.b(DashoA13*..)
      at com.sun.crypto.provider.AESCipher.engineDoFinal(DashoA13*..)
      at javax.crypto.Cipher.doFinal(DashoA13*..)
      at javax.crypto.CipherOutputStream.close(DashoA13*..)
      at java.util.zip.DeflaterOutputStream.close(Unknown Source)
      at gwtdistcc.client.CompileUtils.encryptFile(CompileUtils.java:294)
      at gwtdistcc.client.BuildSlave.doBuild(BuildSlave.java:488)
      at gwtdistcc.client.BuildSlave$Build.run(BuildSlave.java:72)
      at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.lang.Thread.run(Unknown Source)

}}}

```

Original issue reported on code.google.com by `dob...@gmail.com` on 10 Aug 2010 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
Probably caused by using the Cipher in multiple threads.  I'll close this for 
now and re-open if I see the issue again.
```

Original comment by `dob...@gmail.com` on 10 Aug 2010 at 8:17
- Changed state: **Done**
